In [1]:
import os
import pandas as pd
import numpy as np

In [ ]:
df77 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201807_train_승인매출정보.parquet")
df88= pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201808_train_승인매출정보.parquet")
df99= pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201809_train_승인매출정보.parquet")
df1010 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201810_train_승인매출정보.parquet")
df1111 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201811_train_승인매출정보.parquet")
df1212 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201812_train_승인매출정보.parquet")

In [ ]:
dfs = [df77, df88, df99, df1010, df1111, df1212]
merged_train_df = pd.concat(dfs, ignore_index=True)

In [ ]:
#메모리 사용 최소화를 위한 데이터 타입 변환 단, 수치형데이터 값을 확인했을때 단위가 일정이상 넘으면 사용하면 안됌
for col, dtype in merged_train_df.dtypes.items():
    if dtype == 'float64':
        merged_train_df[col] = merged_train_df[col].astype('float32')
    elif dtype == 'int64':
        merged_train_df[col] = merged_train_df[col].astype('int32')

In [ ]:
#병합된 데이터 저장
merged_train_df.to_parquet("3.승인정보_all_month.parquet")

In [23]:
df7 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201807_test_승인매출정보.parquet")
df8 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201808_test_승인매출정보.parquet")
df9 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201809_test_승인매출정보.parquet")
df10 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201810_test_승인매출정보.parquet")
df11 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201811_test_승인매출정보.parquet")
df12 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\test\3.승인매출정보\201812_test_승인매출정보.parquet")

In [24]:
dfs = [df7, df8, df9, df10, df11, df12]
merged_df = pd.concat(dfs, ignore_index=True)

In [5]:
for col, dtype in merged_df.dtypes.items():
    if dtype == 'float64':
        merged_df[col] = merged_df[col].astype('float32')
    elif dtype == 'int64':
        merged_df[col] = merged_df[col].astype('int32')

In [6]:
merged_df.to_parquet("3.승인정보_all_month_test.parquet")

In [ ]:
#병합된 데이터 불러오기
df = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\project\3.승인정보_all_month.parquet")
df1 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\project\3.승인정보_all_month_test.parquet")

In [ ]:
# train 컬럼중 고유값이 1개인 컬럼 드랍
"""['이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M', '여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액',
  '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 
 'RP후경과월_유선방송', 'RP후경과월_건강', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '이용개월수_당사페이_R6M', '이용금액_당사페이_R6M', 
'이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용건수_당사페이_R3M', 
'이용건수_당사기타_R3M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M']
"""
unique_cols = [col for col in df.columns if df[col].nunique() == 1]
df = df.drop(columns=unique_cols)
print(f"드랍된 컬럼: {unique_cols}")

드랍된 컬럼: ['이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M', '여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP후경과월_유선방송', 'RP후경과월_건강', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '이용개월수_당사페이_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M']

In [ ]:
#train 기준으로 컬럼 드랍
# 제거할 컬럼 리스트
#단순 추후확인용 변수 코드에는 위에서 사용한 변수 사용하여 제거
drop_cols = [
    '이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M', '여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액',
    '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M',
    'RP후경과월_유선방송', 'RP후경과월_건강', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '이용개월수_당사페이_R6M', '이용금액_당사페이_R6M',
    '이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용건수_당사페이_R3M',
    '이용건수_당사기타_R3M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M'
]

# 실제 존재하는 컬럼만 제거
cols_to_drop = [col for col in unique_cols if col in df1.columns]
df1 = df1.drop(columns=cols_to_drop)

In [74]:
print(f"컬럼 총 개수: {df.shape[1]}")
print(f"컬럼 총 개수: {df1.shape[1]}")

컬럼 총 개수: 375
컬럼 총 개수: 375

In [56]:
print(f"드랍된 컬럼 개수: {len(unique_cols)}")
print(f"드랍된 컬럼 개수: {len(unique_cols)}")

드랍된 컬럼 개수: 31
드랍된 컬럼 개수: 31

In [75]:
# 범주형 데이터 중 결측치가 있는 컬럼을 찾아 '기타'로 채우기
cat_cols = df.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna('기타')
        print(f"{col} 컬럼의 결측치를 '기타'로 채움")

_1순위업종 컬럼의 결측치를 '기타'로 채움
_2순위업종 컬럼의 결측치를 '기타'로 채움
_3순위업종 컬럼의 결측치를 '기타'로 채움
_1순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_2순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_3순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_1순위교통업종 컬럼의 결측치를 '기타'로 채움
_2순위교통업종 컬럼의 결측치를 '기타'로 채움
_3순위교통업종 컬럼의 결측치를 '기타'로 채움
_1순위여유업종 컬럼의 결측치를 '기타'로 채움
_2순위여유업종 컬럼의 결측치를 '기타'로 채움
_3순위여유업종 컬럼의 결측치를 '기타'로 채움
_1순위납부업종 컬럼의 결측치를 '기타'로 채움
_2순위납부업종 컬럼의 결측치를 '기타'로 채움
_3순위납부업종 컬럼의 결측치를 '기타'로 채움
최종카드론_신청경로코드 컬럼의 결측치를 '기타'로 채움

In [76]:
# 범주형 데이터 중 결측치가 있는 컬럼을 찾아 '기타'로 채우기
cat_cols = df1.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    if df1[col].isnull().any():
        df1[col] = df1[col].fillna('기타')
        print(f"{col} 컬럼의 결측치를 '기타'로 채움")

_1순위업종 컬럼의 결측치를 '기타'로 채움
_2순위업종 컬럼의 결측치를 '기타'로 채움
_3순위업종 컬럼의 결측치를 '기타'로 채움
_1순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_2순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_3순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_1순위교통업종 컬럼의 결측치를 '기타'로 채움
_2순위교통업종 컬럼의 결측치를 '기타'로 채움
_3순위교통업종 컬럼의 결측치를 '기타'로 채움
_1순위여유업종 컬럼의 결측치를 '기타'로 채움
_2순위여유업종 컬럼의 결측치를 '기타'로 채움
_3순위여유업종 컬럼의 결측치를 '기타'로 채움
_1순위납부업종 컬럼의 결측치를 '기타'로 채움
_2순위납부업종 컬럼의 결측치를 '기타'로 채움
_3순위납부업종 컬럼의 결측치를 '기타'로 채움
최종카드론_신청경로코드 컬럼의 결측치를 '기타'로 채움

In [ ]:
# 날짜(YYYYMMDD) 또는 '사용하지 않음'(예: 10101) 패턴을 가진 int 컬럼 자동 탐지 및 전처리

def is_date_or_unused_col(series):
    # int 타입, 값이 100000 이하(사용안함) 또는 8자리(YYYYMMDD)인 값이 많으면 True
    if not np.issubdtype(series.dtype, np.integer):
        return False
    vals = series.dropna().unique()
    # 8자리(YYYYMMDD)와 100000 이하 값이 전체의 90% 이상이면 해당 패턴으로 간주
    date_like = sum((v > 10000000) & (v < 30000000) for v in vals)
    unused_like = sum(v == 10101 for v in vals)
    ratio = (date_like + unused_like) / len(vals) if len(vals) > 0 else 0
    return ratio > 0.9

for col in df.columns:
    if is_date_or_unused_col(df[col]):
        def parse_date_or_unused(x):
            if x == 10101:
                return pd.Timestamp('2262-04-11')
            try:
                return pd.to_datetime(str(int(x)), format='%Y%m%d')
            except:
                return np.nan
        df[col] = df[col].apply(parse_date_or_unused)
        print(f"{col} 컬럼을 날짜/2262-04-11 패턴으로 자동 전처리")

최종이용일자_기본 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_신판 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_CA 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_카드론 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_체크 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_일시불 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_할부 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리

In [ ]:


for col in df1.columns:
    if is_date_or_unused_col(df1[col]):
        def parse_date_or_unused(x):
            if x == 10101:
                return pd.Timestamp('2262-04-11') #최대지원날짜
            try:
                return pd.to_datetime(str(int(x)), format='%Y%m%d')
            except:
                return np.nan
        df1[col] = df1[col].apply(parse_date_or_unused)
        print(f"{col} 컬럼을 날짜/2262-04-11 패턴으로 자동 전처리")

최종이용일자_기본 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_신판 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_CA 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_카드론 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_체크 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_일시불 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리
최종이용일자_할부 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리

In [84]:
# '최종카드론_금융상환방식코드' 컬럼의 결측치를 최빈값으로 채우기
df['최종카드론_금융상환방식코드'] = df['최종카드론_금융상환방식코드'].fillna(df['최종카드론_금융상환방식코드'].mode()[0])
df1['최종카드론_금융상환방식코드'] = df1['최종카드론_금융상환방식코드'].fillna(df1['최종카드론_금융상환방식코드'].mode()[0])

In [85]:
df['최종카드론_금융상환방식코드'] = df['최종카드론_금융상환방식코드'].astype('object')
print(df['최종카드론_금융상환방식코드'].dtype)
df1['최종카드론_금융상환방식코드'] = df1['최종카드론_금융상환방식코드'].astype('object')
print(df1['최종카드론_금융상환방식코드'].dtype)

object
object

In [ ]:
#데이터 타입 변경
df['최종카드론_대출일자'] = pd.to_datetime(df['최종카드론_대출일자'], format='%Y%m%d', errors='coerce')
df1['최종카드론_대출일자'] = pd.to_datetime(df1['최종카드론_대출일자'], format='%Y%m%d', errors='coerce')

In [88]:
#결측치 앞뒤날짜기준으로
df['최종카드론_대출일자'] = df['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')
df1['최종카드론_대출일자'] = df1['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rtc32\AppData\Local\Temp\ipykernel_10884\3652562372.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['최종카드론_대출일자'] = df['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')
C:\Users\rtc32\AppData\Local\Temp\ipykernel_10884\3652562372.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1['최종카드론_대출일자'] = df1['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')

In [ ]:
#상관계수가 1인 컬럼제거 할부건수_부분_12MR12M <-> 이용건수부분무이자_R12M : 1.0 <- 삭제기준 데이터가 한값(0)에 치우친것 우선 삭제

df = df.drop(columns=['이용건수_부분무이자_R12M'])
df1 = df1.drop(columns=['이용건수_부분무이자_R12M'])

In [ ]:

for col in df1.columns:
    print(f"컬럼명: {col}")
    print(f" - 데이터 타입: {df1[col].dtype}")
    print(f" - 고유값(최대 10개): {df1[col].unique()[:10]}")
    print("-" * 40)

컬럼명: 기준년월
 - 데이터 타입: int32
 - 고유값(최대 10개): [201807 201808 201809 201810 201811 201812]
----------------------------------------
컬럼명: ID
 - 데이터 타입: object
 - 고유값(최대 10개): ['TEST_00000' 'TEST_00001' 'TEST_00002' 'TEST_00003' 'TEST_00004'
 'TEST_00005' 'TEST_00006' 'TEST_00007' 'TEST_00008' 'TEST_00009']
----------------------------------------
컬럼명: 최종이용일자_기본
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-31 00:00:00', '2018-07-25 00:00:00', '2018-07-11 00:00:00',
 '2018-07-16 00:00:00', '2018-02-23 00:00:00', '2018-07-17 00:00:00',
 '2018-07-01 00:00:00', '2018-07-05 00:00:00', '2018-07-23 00:00:00',
 '2018-07-29 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_신판
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-31 00:00:00', '2018-07-25 00:00:00', '2018-07-11 00:00:00',
 '2018-07-16 00:00:00', '2018-02-23 00:00:00', '2018-07-17 00:00:00',
 '2018-07-01 00:00:00', '2018-07-05 00:00:00', '2018-07-23 00:00:00',
 '2018-07-29 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_CA
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2262-04-11 00:00:00', '2017-07-10 00:00:00', '2015-08-22 00:00:00',
 '2013-09-17 00:00:00', '2015-04-06 00:00:00', '2012-10-10 00:00:00',
 '2016-08-10 00:00:00', '2015-11-27 00:00:00', '2015-04-02 00:00:00',
 '2018-03-11 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_카드론
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2262-04-11 00:00:00', '2017-11-07 00:00:00', '2015-08-01 00:00:00',
 '2015-08-03 00:00:00', '2017-06-28 00:00:00', '2016-12-10 00:00:00',
 '2017-12-02 00:00:00', '2018-06-16 00:00:00', '2016-05-07 00:00:00',
 '2018-03-08 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_체크
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2262-04-11 00:00:00', '2018-07-31 00:00:00', '2018-07-07 00:00:00',
 '2017-01-31 00:00:00', '2018-07-06 00:00:00', '2017-07-31 00:00:00',
 '2014-01-17 00:00:00', '2016-07-31 00:00:00', '2014-08-20 00:00:00',
 '2015-03-01 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_일시불
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-31 00:00:00', '2018-07-25 00:00:00', '2018-07-11 00:00:00',
 '2018-07-16 00:00:00', '2017-09-11 00:00:00', '2018-07-17 00:00:00',
 '2017-06-15 00:00:00', '2018-07-01 00:00:00', '2018-07-05 00:00:00',
 '2018-07-23 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_할부
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2016-09-13 00:00:00', '2018-07-22 00:00:00', '2016-07-03 00:00:00',
 '2016-07-01 00:00:00', '2018-07-08 00:00:00', '2018-02-23 00:00:00',
 '2018-02-01 00:00:00', '2016-12-12 00:00:00', '2018-06-20 00:00:00',
 '2262-04-11 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 이용건수_신용_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [28  8 59 37 19 -2 43 -1  6  4]
----------------------------------------
컬럼명: 이용건수_신판_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [28  8 59 37 19 -2 43 -1  6  4]
----------------------------------------
컬럼명: 이용건수_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [28  6 59 37 18 -2 43 -1  4  5]
----------------------------------------
컬럼명: 이용건수_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 2 1 3]
----------------------------------------
컬럼명: 이용건수_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 2 1]
----------------------------------------
컬럼명: 이용건수_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 2 3 1]
----------------------------------------
컬럼명: 이용건수_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 22 11 46 15 13 23 52  8 26]
----------------------------------------
컬럼명: 이용건수_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [7650  367 8547 1270  709    0 9948 2833 2171 3862]
----------------------------------------
컬럼명: 이용금액_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 3882 4989 4692 5304 4616 7981 4319 4751 4384]
----------------------------------------
컬럼명: 이용금액_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 5304 4353 5367 5856 5334 4058 4747 4575 3973]
----------------------------------------
컬럼명: 이용금액_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 3882 4989 4692 4616 3628 4319 4751 4384 4631]
----------------------------------------
컬럼명: 이용금액_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 16392  5911  6355  8732  6975 10357  7288 14779 13748]
----------------------------------------
컬럼명: 이용금액_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4420  2770 10022  3069  3289  4495 11380  1867  3793]
----------------------------------------
컬럼명: 이용금액_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 69624 68607 68034 68175 69342 69838 69052 70198 69902]
----------------------------------------
컬럼명: 이용후경과월_신용
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  1  8  4  3  2 12  9 11  5]
----------------------------------------
컬럼명: 이용후경과월_신판
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  1  8  4  3  2 12  9 11  5]
----------------------------------------
컬럼명: 이용후경과월_일시불
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 10 12  1  9  2  3  5 11  8]
----------------------------------------
컬럼명: 이용후경과월_할부
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  0  1  2  8  4  7  9  3  6]
----------------------------------------
컬럼명: 이용후경과월_할부_유이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  3  1  5  8  4  6  2  0  9]
----------------------------------------
컬럼명: 이용후경과월_할부_무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  0  3  2  8  7  9  1  6  4]
----------------------------------------
컬럼명: 이용후경과월_부분무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  2  5  7  1  8  9  4  6 10]
----------------------------------------
컬럼명: 이용후경과월_CA
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  4  9  1  0  8  2  5 10  3]
----------------------------------------
컬럼명: 이용후경과월_체크
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  0  3 10  1  2  4  5  7  8]
----------------------------------------
컬럼명: 이용후경과월_카드론
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  8  7  1  4  6 10  2  3  9]
----------------------------------------
컬럼명: 이용건수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [150  28 650 361 227  50 489 179  78 263]
----------------------------------------
컬럼명: 이용건수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [150  22 650 361 227  50 489 179  78 263]
----------------------------------------
컬럼명: 이용건수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [150  -1 641 357 215  50 489 179  78 255]
----------------------------------------
컬럼명: 이용건수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 23  9  4 12  8  5  3 14 16]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  4  3 10  5 11  7  9  8 13]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 23  9  8  4  5  3 11  6 12]
----------------------------------------
컬럼명: 이용건수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6  4  3  8 19  5 13  2 12]
----------------------------------------
컬럼명: 이용건수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 227  13  64 524 206  28  25  50 264]
----------------------------------------
컬럼명: 이용건수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 49063   7771  73003   7421  10493   6878 107219  14995  36107  72619]
----------------------------------------
컬럼명: 이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 34054 31830  8939 13983  7838  6670  4410 21025  1879]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  9249 11073  3803  4099  6264  4419  4410  5332  4065]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 17396 20756  5136  9884  1573  2251 15693  1879 19384]
----------------------------------------
컬럼명: 이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 7409 8097 8024 8029 7258 7621 7437 8492 7841]
----------------------------------------
컬럼명: 이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  12015  22272   5902  23868   3820 289146   7344   9264  32721]
----------------------------------------
컬럼명: 이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1752 46255  1004  -414  6412  7392 78019 43133  2436  3793]
----------------------------------------
컬럼명: 이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  46678  46890  46767  47601  46013  46405  46029 137909  46727]
----------------------------------------
컬럼명: 최대이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [21700  2423 12667  1661  1082  3318 12083  1861 14880 23935]
----------------------------------------
컬럼명: 최대이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  6547 16178  2628  4082  6513  4204  8189  6911 12068]
----------------------------------------
컬럼명: 최대이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 5483 6497 2628 2317 6513 4204 8189 4565 4704]
----------------------------------------
컬럼명: 최대이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  5441 16178  4082  1634  1220  6911 12068  2320 11447]
----------------------------------------
컬럼명: 최대이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 6547 7176 7306 7143 6566 7060 6501 7882 7223]
----------------------------------------
컬럼명: 최대이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  5548 10966  4241  8623  2331 34727  3728  5324  8139]
----------------------------------------
컬럼명: 최대이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4275  2802  1299 32490  7223  1389  3589  2567  6390]
----------------------------------------
컬럼명: 최대이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  74184  74871  74825  76658  20600  20305  20651 140391  40883]
----------------------------------------
컬럼명: 이용개월수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [10  9 12  2 11  8  3  0  1  6]
----------------------------------------
컬럼명: 이용개월수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [10  9 12  2 11  8  3  0  1  6]
----------------------------------------
컬럼명: 이용개월수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [10  9 12  3  4 11  8  2  0  1]
----------------------------------------
컬럼명: 이용개월수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 10  7  2  1  4  3  9  8  5]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 3 2 4 5]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 9 5 1 6 3 4 7 8 2]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  4  3  2  5  9  7  8  1 12]
----------------------------------------
컬럼명: 이용개월수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 12  8  3  4  6  5  7  2  9]
----------------------------------------
컬럼명: 이용개월수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 72  31 360 223 119  -2 281  -1  11  79]
----------------------------------------
컬럼명: 이용건수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 72  27 360 223 119  -2 281  -1  11  79]
----------------------------------------
컬럼명: 이용건수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 72  10 354 221 112  -2 281  11  76  15]
----------------------------------------
컬럼명: 이용건수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 17  6  2  7  1  3 11 14 10]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  1  3  2 -1  4  5  6]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 15  3  1  6  2  9 14  8  4]
----------------------------------------
컬럼명: 이용건수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  4  3 10  7  8  2  6  1 13]
----------------------------------------
컬럼명: 이용건수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 133   5 286  87  22  13  20 144 316]
----------------------------------------
컬럼명: 이용건수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용금액_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [26595 -7578 48483   403  1238     0 68303 15156 19846 19540]
----------------------------------------
컬럼명: 이용금액_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 25075 22960  2432 13165  8986  7567  9631  4931  5631]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 -1358  9699  3118  3832  8986 14257 -9050  6123 19142]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 16654 13260  -685  9332  7567  9631  4931  5631  9018]
----------------------------------------
컬럼명: 이용금액_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  9779  9952  9824 10107 10492 10644 10373 10425 10073]
----------------------------------------
컬럼명: 이용금액_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0   8382  14415  13389   3878 163314   5857  19768  19537   5298]
----------------------------------------
컬럼명: 이용금액_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 26602  2378 62869 17053  7051  5593  5567 28173 70301]
----------------------------------------
컬럼명: 이용금액_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 56531 52978 38943 43765 78808 71892 50185 45278 69492]
----------------------------------------
컬럼명: 이용개월수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [5 6 0 1 2 4 3]
----------------------------------------
컬럼명: 이용개월수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [5 6 0 1 2 4 3]
----------------------------------------
컬럼명: 이용개월수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [5 6 0 2 1 4 3]
----------------------------------------
컬럼명: 이용개월수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 6 3 1 4 2 5]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3 4 5 6]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 6 1 4 2 3 5]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 3 6 4 5 2]
----------------------------------------
컬럼명: 이용개월수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 6 5 1 4 2 3]
----------------------------------------
컬럼명: 이용개월수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 66  31 194 117  60   0 150   2  17  18]
----------------------------------------
컬럼명: 이용건수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 66  28 194 117  60   0 150   2  17  18]
----------------------------------------
컬럼명: 이용건수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 66  21 192 115  56   0 150   2  16  18]
----------------------------------------
컬럼명: 이용건수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 7 2 4 1 5 3 6 8 9]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  1  2  3 -1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6  1  3  4  2  5 -1]
----------------------------------------
컬럼명: 이용건수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 3 2 5 4 7 1 6 8 9]
----------------------------------------
컬럼명: 이용건수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0  63   4 145  40   8  12  73 162   2]
----------------------------------------
컬럼명: 이용건수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [20503 -1832 25225  2670  2982 -1681 38546 -2456  6572  4973]
----------------------------------------
컬럼명: 이용금액_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  -36 11950  6036  2818  9960     7     9    -9     1  6668]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  2257  6032  4081  9447 -3695 10521  6574  5124  4772]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  8927  2739  5846  6606  3603  5217 10284 10318 11156]
----------------------------------------
컬럼명: 이용금액_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-36 765   3  79  32   7   9  -9   1  62]
----------------------------------------
컬럼명: 이용금액_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  5293  6350  2735 77164  3907  9114 10020  4713 20598]
----------------------------------------
컬럼명: 이용금액_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 12593  1613 32215  8126  3299  3540 14683 36166   324]
----------------------------------------
컬럼명: 이용금액_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 72251 71356 61112 69255 79264 79190 73995 80150 72309]
----------------------------------------
컬럼명: 이용개월수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 2 1]
----------------------------------------
컬럼명: 이용개월수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 2 1]
----------------------------------------
컬럼명: 이용개월수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 2 1]
----------------------------------------
컬럼명: 이용개월수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 3 1 2]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 3 1 2]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 3 2]
----------------------------------------
컬럼명: 이용개월수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 3 2 1]
----------------------------------------
컬럼명: 이용개월수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용가맹점수
 - 데이터 타입: int32
 - 고유값(최대 10개): [43 20 79 23 28  0 75  4 26  1]
----------------------------------------
컬럼명: 이용금액_해외
 - 데이터 타입: int32
 - 고유값(최대 10개): [1655    0 1705 2006 1300 1698 2856 1598 1681  931]
----------------------------------------
컬럼명: 쇼핑_도소매_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1033 1679  824  890 2002  885 1645 1820 1200]
----------------------------------------
컬럼명: 쇼핑_백화점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 643    0  760  871  885  651  608 1136 1002 1036]
----------------------------------------
컬럼명: 쇼핑_마트_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 854 1154 1064  804  774    0  906  751 1489 1349]
----------------------------------------
컬럼명: 쇼핑_슈퍼마켓_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 350    0 1094  634  323 1135  491  942  994  567]
----------------------------------------
컬럼명: 쇼핑_편의점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 236    0 1178  145  213 1436  181  307  333  529]
----------------------------------------
컬럼명: 쇼핑_아울렛_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 565 508 636 511 451 521 608 504 467]
----------------------------------------
컬럼명: 쇼핑_온라인_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [1393 4463  610    0  578  258 5410  551 5836 4400]
----------------------------------------
컬럼명: 쇼핑_기타_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [200   0 368 397 250 324 288 287 611 358]
----------------------------------------
컬럼명: 교통_주유이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [1204 1278 2022    0 2840 1261 2020 1296 1679 1186]
----------------------------------------
컬럼명: 교통_정비이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 482 301 398 307 340 295 325 565 343]
----------------------------------------
컬럼명: 교통_통행료이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 274 288 283 282 289 299 278 284 286]
----------------------------------------
컬럼명: 교통_버스지하철이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 189    0  174 1419  527 1127  272  961  670 1138]

In [96]:
for col in df.columns:
    print(f"컬럼명: {col}")
    print(f" - 데이터 타입: {df[col].dtype}")
    print(f" - 고유값(최대 10개): {df[col].unique()[:10]}")
    print("-" * 40)

컬럼명: 기준년월
 - 데이터 타입: int32
 - 고유값(최대 10개): [201807 201808 201809 201810 201811 201812]
----------------------------------------
컬럼명: ID
 - 데이터 타입: object
 - 고유값(최대 10개): ['TRAIN_000000' 'TRAIN_000001' 'TRAIN_000002' 'TRAIN_000003'
 'TRAIN_000004' 'TRAIN_000005' 'TRAIN_000006' 'TRAIN_000007'
 'TRAIN_000008' 'TRAIN_000009']
----------------------------------------
컬럼명: 최종이용일자_기본
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-19 00:00:00', '2018-07-06 00:00:00', '2018-07-21 00:00:00',
 '2018-01-24 00:00:00', '2016-04-25 00:00:00', '2018-07-31 00:00:00',
 '2018-07-26 00:00:00', '2018-07-10 00:00:00', '2262-04-11 00:00:00',
 '2018-06-05 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_신판
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-13 00:00:00', '2018-07-19 00:00:00', '2018-07-06 00:00:00',
 '2018-07-15 00:00:00', '2018-01-24 00:00:00', '2016-04-25 00:00:00',
 '2018-07-31 00:00:00', '2018-07-26 00:00:00', '2018-07-10 00:00:00',
 '2262-04-11 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_CA
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-19 00:00:00', '2017-07-28 00:00:00', '2018-07-06 00:00:00',
 '2018-07-21 00:00:00', '2262-04-11 00:00:00', '2013-08-26 00:00:00',
 '2015-07-08 00:00:00', '2014-04-29 00:00:00', '2015-11-07 00:00:00',
 '2018-06-16 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_카드론
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2262-04-11 00:00:00', '2017-03-27 00:00:00', '2015-11-19 00:00:00',
 '2018-06-05 00:00:00', '2018-02-06 00:00:00', '2016-06-30 00:00:00',
 '2015-01-14 00:00:00', '2015-05-14 00:00:00', '2014-10-18 00:00:00',
 '2015-07-02 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_체크
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-02-03 00:00:00', '2262-04-11 00:00:00', '2014-12-30 00:00:00',
 '2014-11-11 00:00:00', '2018-05-12 00:00:00', '2018-07-31 00:00:00',
 '2015-01-20 00:00:00', '2018-07-21 00:00:00', '2018-07-07 00:00:00',
 '2014-03-01 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_일시불
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-09 00:00:00', '2018-07-19 00:00:00', '2018-07-06 00:00:00',
 '2018-07-04 00:00:00', '2018-01-24 00:00:00', '2016-04-25 00:00:00',
 '2018-07-31 00:00:00', '2018-07-26 00:00:00', '2018-07-10 00:00:00',
 '2262-04-11 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_할부
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-13 00:00:00', '2017-12-31 00:00:00', '2018-06-27 00:00:00',
 '2018-07-15 00:00:00', '2262-04-11 00:00:00', '2017-05-28 00:00:00',
 '2018-03-20 00:00:00', '2018-04-11 00:00:00', '2015-07-01 00:00:00',
 '2018-03-29 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 이용건수_신용_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [11 13 12  6 -2  0  9 27 77  1]
----------------------------------------
컬럼명: 이용건수_신판_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 9 13 10  4 -2  0 27 77  1 -3]
----------------------------------------
컬럼명: 이용건수_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 8 13 10  3 -2  0  9 27 77  1]
----------------------------------------
컬럼명: 이용건수_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3]
----------------------------------------
컬럼명: 이용건수_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2]
----------------------------------------
컬럼명: 이용건수_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 1 3]
----------------------------------------
컬럼명: 이용건수_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  8 12 41 23 10 19 32 31 18]
----------------------------------------
컬럼명: 이용건수_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1995  2862  5854   387     0  3334  2728 24242  2965  3410]
----------------------------------------
컬럼명: 이용금액_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4961  8490 10596  3495  3946  3700  8997  3640  4410]
----------------------------------------
컬럼명: 이용금액_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 4457 5432 4359 4397 3771 3927 4483 4595 5218]
----------------------------------------
컬럼명: 이용금액_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 4961 4032 5163 3495 3946 3700 4637 3640 4410]
----------------------------------------
컬럼명: 이용금액_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12209     0 14306 13789  9510 10914 18817  5883 12820 10395]
----------------------------------------
컬럼명: 이용금액_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1525 2544 8877 4488 1721 4718 7004 5493 3092]
----------------------------------------
컬럼명: 이용금액_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 68522 70061 69768 69695 69010 70558 70824 69610 69788]
----------------------------------------
컬럼명: 이용후경과월_신용
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  1  8  9  4 10 11  2]
----------------------------------------
컬럼명: 이용후경과월_신판
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  1  8  9  4  2 10 11]
----------------------------------------
컬럼명: 이용후경과월_일시불
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  2  9 11  1  8 10  3]
----------------------------------------
컬럼명: 이용후경과월_할부
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2  9  0  1 12  4  5  7  3  8]
----------------------------------------
컬럼명: 이용후경과월_할부_유이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 7  9 12  1  8  4  3  0  5  2]
----------------------------------------
컬럼명: 이용후경과월_할부_무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2  9  0  1 12  4  5  7  3  8]
----------------------------------------
컬럼명: 이용후경과월_부분무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  2  7  5  1  8  6  4  9 10]
----------------------------------------
컬럼명: 이용후경과월_CA
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 12  1  6  2  7 11  9  4  5]
----------------------------------------
컬럼명: 이용후경과월_체크
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5 12  2  0  6  1  9 11  4  8]
----------------------------------------
컬럼명: 이용후경과월_카드론
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  1  5  2  8  4  3  7  6  9]
----------------------------------------
컬럼명: 이용건수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [165 204 148 105  -1   0 369 863  34 129]
----------------------------------------
컬럼명: 이용건수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [146 202 134  85  -1   0 148 369 863  34]
----------------------------------------
컬럼명: 이용건수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [143 202 131  74  -1   0 148 366 863  27]
----------------------------------------
컬럼명: 이용건수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0 11  7  9  4 24 36 12  8]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  5  4 12  8 13  7  6  3 10]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  6  7  5  4 12 28  8 15]
----------------------------------------
컬럼명: 이용건수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [19  2 14 20  0  4  6  1 12  3]
----------------------------------------
컬럼명: 이용건수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 30   0  24  85 123 472 281 141 135 381]
----------------------------------------
컬럼명: 이용건수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 20667  54341  55656  10753  -2129      0  51382  25691 360859  34884]
----------------------------------------
컬럼명: 이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 9431  6134 10561 22129     0  3939  4014  2204 34252  6374]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3602  4058     0 10031  3939  6397 22210  4067 22016  4801]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5828  2076 10561 12098     0  4014  2204 25891  6374 12642]
----------------------------------------
컬럼명: 이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 8361 7983 8163 7682 7754 7922 8158 8001 8045]
----------------------------------------
컬럼명: 이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [103812   4297 374552 207745      0   9797  18355  11167  72974   3902]
----------------------------------------
컬럼명: 이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 6474  -414   871 10754   558   144 13933  5588  -332  1351]
----------------------------------------
컬럼명: 이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  46585  46741 134652  46762 140841  46578  47052  46657  47222]
----------------------------------------
컬럼명: 최대이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 4906 10407 10112  3075    62     0  7318  3581 47166  6681]
----------------------------------------
컬럼명: 최대이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4607 15453  8874  3646  3105  5979 25808 10391  8227]
----------------------------------------
컬럼명: 최대이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4607  3475  3646  2494 11037  4966 17410  3096  9121]
----------------------------------------
컬럼명: 최대이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  2321 15453  8874  3105  5979 25808 10391  8227  7351]
----------------------------------------
컬럼명: 최대이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 7839 7237 7219 7354 7410 7343 7508 7472 7240]
----------------------------------------
컬럼명: 최대이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [11710  3377 65977 19698     0  5127  6735  6150 12852  3381]
----------------------------------------
컬럼명: 최대이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1020     0  3324  3372  5158 24605  7714  3900  7980 14033]
----------------------------------------
컬럼명: 최대이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  41320  41305  76400 141210  20752  74408  20944  74166  20575]
----------------------------------------
컬럼명: 이용개월수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  1  0  7  2 11 10  3  6]
----------------------------------------
컬럼명: 이용개월수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  1  0  7  2 11 10  3  6]
----------------------------------------
컬럼명: 이용개월수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  7  1  0  6  2 11 10  8]
----------------------------------------
컬럼명: 이용개월수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5  2  8  0  1  4 10 11  7  3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 4 3 2 5]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [4 1 2 5 0 3 7 9 8 6]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  2  8  0  3  5  7  1 10  6]
----------------------------------------
컬럼명: 이용개월수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  8 12  7  9  6  5  4  2]
----------------------------------------
컬럼명: 이용개월수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 77  81  62  42  -2   8  55 177 455   1]
----------------------------------------
컬럼명: 이용건수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 67  81  56  32  -2   8  55 177 455   1]
----------------------------------------
컬럼명: 이용건수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 64  81  54  26  -2   8  55 176 454  16]
----------------------------------------
컬럼명: 이용건수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  2  6  1  4 11 19  8  7]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  4  1 -1  2  3  5  6]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  2  1  4  7 15  8  9 11]
----------------------------------------
컬럼명: 이용건수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [10  0  6  2  3  1  9 12  7  4]
----------------------------------------
컬럼명: 이용건수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 22   0   8  40  52 258 139  59  69 200]
----------------------------------------
컬럼명: 이용건수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용금액_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  8380  19426  35136  -7031    957      0  22495  19968 131028  19802]
----------------------------------------
컬럼명: 이용금액_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-1654     0 14871 16531 -1614 25136  6030  8480  5119  6915]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  7992  4799 13658 24347  2606  8646  8534  6680  2387]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-1654     0 14871  8538 -1614 25136  6030  8480  5119  2116]
----------------------------------------
컬럼명: 이용금액_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 10214 10532 10509 10418 10383 10710 10591 10271 10027]
----------------------------------------
컬럼명: 이용금액_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 59452      0 134858  95337   6081   8023   7934  41584  16512   4237]
----------------------------------------
컬럼명: 이용금액_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 4090     0  3610  5993 10281 58336 27145  8593 18542 43453]
----------------------------------------
컬럼명: 이용금액_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  56122 102000  48771  58179  40215  44239  68206  85039  62456]
----------------------------------------
컬럼명: 이용개월수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 4 1 6 5 3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 2 3 1 4 5 6]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 3 1 6 4 5]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 0 5 1 3 4 2]
----------------------------------------
컬럼명: 이용개월수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 4 6 5 2 3]
----------------------------------------
컬럼명: 이용개월수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 27  43  36  21   0  79 246   8 193 100]
----------------------------------------
컬럼명: 이용건수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 22  43  33  16   0  21  79 246   8 193]
----------------------------------------
컬럼명: 이용건수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 21  43  31  13   0  79 245  -2   8 193]
----------------------------------------
컬럼명: 이용건수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3 5 7 4 6 8 9]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  2  1  3 -1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1  0  2  3  5  4  6 -1]
----------------------------------------
컬럼명: 이용건수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [5 0 3 2 1 4 7 6 8 9]
----------------------------------------
컬럼명: 이용건수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0  20  26 133  75  30  35  99  95  47]
----------------------------------------
컬럼명: 이용건수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2877 14316 15694 -2710 -3383  -210 11254  9105 63825   331]
----------------------------------------
컬럼명: 이용금액_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1949   -25 11458 11662    -1   -23    -4    19    18    24]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  5989  3801  8504 13824  5418  4470  3045  7489  4328]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1984     0 11308  5643 11608  7260  5143  5944 13831  4794]
----------------------------------------
컬럼명: 이용금액_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-34 -25 150  29  -1 -23  -4  19  18  24]
----------------------------------------
컬럼명: 이용금액_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [37417     0 43002 47830  5424  4076  7103 20641 11271 30468]
----------------------------------------
컬럼명: 이용금액_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  1087  3131  5241 29197 14570  4733  9578 21735 17633]
----------------------------------------
컬럼명: 이용금액_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 76408 89956 74771 66830 78661 71474 71044 84570 74828]
----------------------------------------
컬럼명: 이용개월수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 3 2]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 2 1]
----------------------------------------
컬럼명: 이용개월수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 3 2]
----------------------------------------
컬럼명: 이용개월수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용가맹점수
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 6 32 27 10  0  1 24 97 83 48]
----------------------------------------
컬럼명: 이용금액_해외
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1885 1648 1331 2077 1342 1300 1561 1460 2562]
----------------------------------------
컬럼명: 쇼핑_도소매_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  645 1038 2162 1567 1434  638 2767  468 2385]
----------------------------------------
컬럼명: 쇼핑_백화점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  751  819  679  879 1274  873  814  856  742]
----------------------------------------
컬럼명: 쇼핑_마트_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  924  801  913 2590 1598 1332  773 1041 1278]
----------------------------------------
컬럼명: 쇼핑_슈퍼마켓_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  435  504  487  225  506 1786 1929 1045  399]
----------------------------------------
컬럼명: 쇼핑_편의점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  315  239  267 1652  705  377  234  181  196]
----------------------------------------
컬럼명: 쇼핑_아울렛_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 642 487 559 599 607 652 613 666 574]
----------------------------------------
컬럼명: 쇼핑_온라인_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0   272  6094   875   984 47249  7643  2230 12350   998]
----------------------------------------
컬럼명: 쇼핑_기타_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [242 289   0 398 384 355 258 252 254 283]
----------------------------------------
컬럼명: 교통_주유이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1215 1362 1361 4347 2958 2163 1356 1273 1863]
----------------------------------------
컬럼명: 교통_정비이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 277 842 483 427 312 273 701 456 621]
----------------------------------------
컬럼명: 교통_통행료이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 284 294 286 280 296 289 283 316 304]
----------------------------------------
컬럼명: 교통_버스지하철이용금액
 - 데이터 타입: int32

In [ ]:
#데이터 저장
df.to_parquet("3.승인매출정보_전처리완(수정).parquet")
df1.to_parquet("3.승인매출정보_test_전처리완(수정).parquet")

In [91]:
df = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\project\3.승인매출정보_전처리완(수정).parquet")

In [92]:
df1 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\project\3.승인매출정보_test_전처리완(수정).parquet")

In [93]:
# df와 df1의 컬럼 비교
df_cols = set(df.columns)
df1_cols = set(df1.columns)

only_in_df = df_cols - df1_cols
only_in_df1 = df1_cols - df_cols

if only_in_df:
    print("df에만 있는 컬럼:", list(only_in_df))
else:
    print("df에만 있는 컬럼 없음")

if only_in_df1:
    print("df1에만 있는 컬럼:", list(only_in_df1))
else:
    print("df1에만 있는 컬럼 없음")

df에만 있는 컬럼 없음
df1에만 있는 컬럼 없음

In [ ]:
#결측치 확인
na_count = df1.isna().sum()
for col, cnt in na_count.items():
    if cnt > 0:
        print(f"{col}: {cnt}개 결측치")